USE DBA
go

DECLARE @DATA DATETIME, @MESES INT

SET @MESES = 3;
SET @DATA = CONVERT (date, GETDATE()-(@MESES*30));
select @DATA as DATA_INICIAL, GETDATE() AS DATA_ATUAL;

SELECT 
DATABASENAME, TAMANHO
from (
SELECT
	DB1.DATA, 
	DB1.DATABASENAME,
	SUM(DB1.FILESIZEMB) AS TAMANHO
	FROM DBO.DBA_INFO_DATABASE AS DB1
	LEFT JOIN 
	(
		SELECT 
		DATA, 
		DATABASENAME,
		SUM(FILESIZEMB) AS TAMANHO
		FROM DBO.DBA_INFO_DATABASE 
		WHERE DATA >=  @DATA
		GROUP BY DATA, DATABASENAME
	)AS DB2
ON	DB1.DATABASENAME = DB2.DATABASENAME AND
DB1.DATA = (DB2.DATA-1)
WHERE DB1.DATA >= CONVERT (date, GETDATE())
GROUP BY DB1.DATABASENAME, DB1.DATA, DB2.TAMANHO
) as teste;

SELECT 
DATABASENAME, SUM(CRESCIMENTO) as [CRESCIMENTO(MB)]
from (
SELECT
	DB1.DATA, 
	DB1.DATABASENAME,
	SUM(DB1.FILESIZEMB) AS TAMANHO,
	ISNULL(
		CASE WHEN DB2.TAMANHO-SUM(DB1.FILESIZEMB) < 0 
			THEN DB2.TAMANHO-SUM(DB1.FILESIZEMB)
		ELSE
			DB2.TAMANHO-SUM(DB1.FILESIZEMB)
		END, 0
		) AS  CRESCIMENTO
	FROM DBO.DBA_INFO_DATABASE AS DB1
	LEFT JOIN 
	(
		SELECT 
		DATA, 
		DATABASENAME,
		SUM(FILESIZEMB) AS TAMANHO
		FROM DBO.DBA_INFO_DATABASE 
		WHERE DATA >=  @DATA
		GROUP BY DATA, DATABASENAME
	)AS DB2
ON	DB1.DATABASENAME = DB2.DATABASENAME AND
DB1.DATA = (DB2.DATA-1)
WHERE DB1.DATA >=  @DATA
GROUP BY DB1.DATABASENAME, DB1.DATA, DB2.TAMANHO
) as teste
GROUP BY DATABASENAME;