USE DBA
go

DECLARE @DATA DATETIME

SET @DATA = '2016-03-01'

SELECT 
	DB1.DATA, 
	DB1.DATABASENAME,
	SUM(DB1.FILESIZEMB) AS TAMANHO,
	SUM(DB1.FREESPACEMB) AS ESPACO_LIVRE,
	ISNULL(
		CASE WHEN (SUM(DB1.FREESPACEMB)-DB2.ESPACO_LIVRE) < 0 
			THEN 0
		ELSE
			(SUM(DB1.FREESPACEMB)-DB2.ESPACO_LIVRE)
		END, 0
		) AS [CRESCIMENTO(MB)]
FROM DBO.DBA_INFO_DATABASE AS DB1
LEFT JOIN 
(
	SELECT 
		DATA, 
		DATABASENAME,
		SUM(FILESIZEMB) AS TAMANHO,
		SUM(FREESPACEMB) AS ESPACO_LIVRE
	FROM DBO.DBA_INFO_DATABASE 
	WHERE DATA >=  @DATA
	GROUP BY DATA, DATABASENAME
)AS DB2
	ON	DB1.DATABASENAME = DB2.DATABASENAME AND
		DB1.DATA = (DB2.DATA-1)
WHERE DB1.DATA >=  @DATA
GROUP BY DB1.DATA, DB1.DATABASENAME, DB2.ESPACO_LIVRE
ORDER BY  DB1.DATABASENAME, DB1.DATA;